/** Static demo data for List Users — frontend only */

export const MANAGE_USERS_STATIC_CENTERS = [
  'Hyderabad',
  'Delhi',
  'Bangalore',
  'Chennai',
  'Vizag',
  'Anantapur',
  'Pune',
  'New Delhi',
]

function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(12, 0, 0, 0)
  return d.toISOString()
}

export const MANAGE_USERS_STATIC_DATA = [
  {
    id: 'usr-001',
    userId: 'USR1001',
    fullName: 'Rahul Sharma',
    email: 'rahul.sharma@gmail.com',
    phone: '9876543210',
    role: 'student',
    assignedCenter: 'Hyderabad',
    status: 'Active',
    joinedAt: daysAgo(2),
    parentName: 'Rajesh Sharma',
    parentPhone: '9876501234',
    profileImage: '',
  },
  {
    id: 'usr-002',
    userId: 'USR1002',
    fullName: 'Anjali Reddy',
    email: 'anjali.reddy@gmail.com',
    phone: '9988776655',
    role: 'admin',
    assignedCenter: 'Bangalore',
    status: 'Active',
    joinedAt: daysAgo(3),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-003',
    userId: 'USR1003',
    fullName: 'Priya Mehta',
    email: 'priya.mehta@sriramias.in',
    phone: '9123456780',
    role: 'student',
    assignedCenter: 'Delhi',
    status: 'Active',
    joinedAt: daysAgo(5),
    parentName: 'Sunil Mehta',
    parentPhone: '9123401234',
    profileImage: '',
  },
  {
    id: 'usr-004',
    userId: 'USR1004',
    fullName: 'Dr. Vikram Singh',
    email: 'vikram.singh@sriramias.in',
    phone: '9012345678',
    role: 'faculty',
    assignedCenter: 'Chennai',
    status: 'Active',
    joinedAt: daysAgo(8),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-005',
    userId: 'USR1005',
    fullName: 'Kavitha Nair',
    email: 'kavitha.nair@gmail.com',
    phone: '9345678901',
    role: 'counselor',
    assignedCenter: 'Vizag',
    status: 'Active',
    joinedAt: daysAgo(10),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-006',
    userId: 'USR1006',
    fullName: 'Arjun Mehta',
    email: 'arjun.mehta@student.sriramias.in',
    phone: '9876543211',
    role: 'student',
    assignedCenter: 'Anantapur',
    status: 'Active',
    joinedAt: daysAgo(12),
    parentName: 'Rajesh Mehta',
    parentPhone: '9876501235',
    profileImage: '',
  },
  {
    id: 'usr-007',
    userId: 'USR1007',
    fullName: 'Suresh Kumar',
    email: 'suresh.kumar@sriramias.in',
    phone: '9456789012',
    role: 'admin',
    assignedCenter: 'Hyderabad',
    status: 'In Active',
    joinedAt: daysAgo(15),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-008',
    userId: 'USR1008',
    fullName: 'Deepa Joshi',
    email: 'deepa.joshi@gmail.com',
    phone: '9567890123',
    role: 'student',
    assignedCenter: 'Pune',
    status: 'Active',
    joinedAt: daysAgo(18),
    parentName: 'Amit Joshi',
    parentPhone: '9567801234',
    profileImage: '',
  },
  {
    id: 'usr-009',
    userId: 'USR1009',
    fullName: 'Prof. Anita Desai',
    email: 'anita.desai@sriramias.in',
    phone: '9678901234',
    role: 'faculty',
    assignedCenter: 'Bangalore',
    status: 'Active',
    joinedAt: daysAgo(22),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-010',
    userId: 'USR1010',
    fullName: 'Rohan Verma',
    email: 'rohan.verma@gmail.com',
    phone: '9789012345',
    role: 'student',
    assignedCenter: 'New Delhi',
    status: 'Active',
    joinedAt: daysAgo(25),
    parentName: 'Vikram Verma',
    parentPhone: '9789001234',
    profileImage: '',
  },
  {
    id: 'usr-011',
    userId: 'USR1011',
    fullName: 'Meera Iyer',
    email: 'meera.iyer@sriramias.in',
    phone: '9890123456',
    role: 'employee',
    assignedCenter: 'Chennai',
    status: 'Active',
    joinedAt: daysAgo(30),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-012',
    userId: 'USR1012',
    fullName: 'Sneha Patel',
    email: 'sneha.patel@gmail.com',
    phone: '9901234567',
    role: 'student',
    assignedCenter: 'Vizag',
    status: 'In Active',
    joinedAt: daysAgo(35),
    parentName: 'Ramesh Patel',
    parentPhone: '9901201234',
    profileImage: '',
  },
  {
    id: 'usr-013',
    userId: 'USR1013',
    fullName: 'Admin User',
    email: 'admin@sriramias.in',
    phone: '9812345678',
    role: 'admin',
    assignedCenter: 'Delhi',
    status: 'Active',
    joinedAt: daysAgo(40),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-014',
    userId: 'USR1014',
    fullName: 'Karthik Rao',
    email: 'karthik.rao@student.sriramias.in',
    phone: '9923456789',
    role: 'student',
    assignedCenter: 'Anantapur',
    status: 'Active',
    joinedAt: daysAgo(45),
    parentName: 'Lakshmi Rao',
    parentPhone: '9923401234',
    profileImage: '',
  },
  {
    id: 'usr-015',
    userId: 'USR1015',
    fullName: 'Dr. Ravi Kumar',
    email: 'ravi.kumar@sriramias.in',
    phone: '9934567890',
    role: 'faculty',
    assignedCenter: 'Hyderabad',
    status: 'Active',
    joinedAt: daysAgo(50),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-016',
    userId: 'USR1016',
    fullName: 'Lakshmi Devi',
    email: 'lakshmi.devi@gmail.com',
    phone: '9945678901',
    role: 'counselor',
    assignedCenter: 'Bangalore',
    status: 'Active',
    joinedAt: daysAgo(55),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
  {
    id: 'usr-017',
    userId: 'USR1017',
    fullName: 'Amit Shah',
    email: 'amit.shah@gmail.com',
    phone: '9956789012',
    role: 'student',
    assignedCenter: 'Chennai',
    status: 'Active',
    joinedAt: daysAgo(60),
    parentName: 'Pradeep Shah',
    parentPhone: '9956701234',
    profileImage: '',
  },
  {
    id: 'usr-018',
    userId: 'USR1018',
    fullName: 'Neha Gupta',
    email: 'neha.gupta@sriramias.in',
    phone: '9967890123',
    role: 'support_staff',
    assignedCenter: 'Pune',
    status: 'In Active',
    joinedAt: daysAgo(65),
    parentName: '',
    parentPhone: '',
    profileImage: '',
  },
]

export function formatManageUserJoinDate(iso) {
  if (!iso) return '—'
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  return d.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export function buildUserFromCreateForm(form, { nextIndex = 1 } = {}) {
  return {
    id: `usr-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    userId: `USR${String(1000 + nextIndex).padStart(4, '0')}`,
    fullName: form.fullName.trim(),
    email: form.email.trim().toLowerCase(),
    phone: form.phone.trim(),
    role: 'student',
    assignedCenter: form.assignedCenter.trim(),
    status: form.status === 'In Active' ? 'In Active' : 'Active',
    joinedAt: new Date().toISOString(),
    parentName: form.parentName.trim(),
    parentPhone: form.parentPhone.trim(),
    profileImage: '',
  }
}
