/**
 * @deprecated Import from `../services/freeResourceService` instead.
 * Re-exports preserve backward compatibility during migration.
 */
export {
  getFreeResourcesList as fetchFreeResourcesList,
  getResourceCategoriesDropdown as fetchResourceCategoriesDropdown,
  createNcertBook,
  getNcertBookById as fetchNcertBookById,
  getNcertBooks as fetchNcertBooks,
  updateNcertBook,
  deleteNcertBook,
  getExamCategoriesDropdown as fetchExamCategoriesDropdown,
  getPaperTypesDropdown as fetchPaperTypesDropdown,
  getYearsDropdown as fetchYearsDropdown,
  createPreviousYearPaper,
  getPreviousYearPaperById as fetchPreviousYearPaperById,
  getPreviousYearPapers as fetchPreviousYearPapers,
  updatePreviousYearPaper,
  deletePreviousYearPaper,
  createMockTest,
  getMockTests as fetchMockTests,
  getMockTestById as fetchMockTestById,
  updateMockTest,
  deleteMockTest,
  getMockTestBulkTemplate as fetchMockTestBulkTemplate,
  uploadMockTestQuestions,
  getMockTestQuestions as fetchMockTestQuestions,
  createMockTestQuestion,
  updateMockTestQuestion,
  duplicateMockTestQuestion,
  deleteMockTestQuestion,
  getStudyMaterialCategoriesDropdown as fetchStudyMaterialCategoriesDropdown,
  createStudyMaterial,
  getStudyMaterials as fetchStudyMaterials,
  getStudyMaterialById as fetchStudyMaterialById,
  updateStudyMaterial,
  deleteStudyMaterial,
  updateFreeResourceStatus,
  getFreeResourceById as fetchFreeResourceById,
  getNcertSubjectsDropdown as fetchNcertSubjectsDropdown,
  getNcertClassesDropdown as fetchNcertClassesDropdown,
  previewMockTestQuestions,
} from '../services/freeResourceService'
